<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Figure 1: TMT-Induced Freezing &amp; CPA | _main.knit</title>
  <meta name="description" content="This bookdown project contains raw data, data analyses, and code to generate analyses for the paper “Corticosterone regulates the balance between freezing and rearing in defensive responses to predator threat”." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Figure 1: TMT-Induced Freezing &amp; CPA | _main.knit" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This bookdown project contains raw data, data analyses, and code to generate analyses for the paper “Corticosterone regulates the balance between freezing and rearing in defensive responses to predator threat”." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Figure 1: TMT-Induced Freezing &amp; CPA | _main.knit" />
  
  <meta name="twitter:description" content="This bookdown project contains raw data, data analyses, and code to generate analyses for the paper “Corticosterone regulates the balance between freezing and rearing in defensive responses to predator threat”." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="figure-2-basal-freezing-before-after-tmt.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">TMT_CORT Book of Data</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a></li>
<li class="chapter" data-level="" data-path="figure-1-tmt-induced-freezing-cpa.html"><a href="figure-1-tmt-induced-freezing-cpa.html"><i class="fa fa-check"></i>Figure 1: TMT-Induced Freezing &amp; CPA</a>
<ul>
<li class="chapter" data-level="" data-path="figure-1-tmt-induced-freezing-cpa.html"><a href="figure-1-tmt-induced-freezing-cpa.html#behavioral-response-during-tmt-presentation"><i class="fa fa-check"></i>Behavioral Response During TMT Presentation</a></li>
<li class="chapter" data-level="" data-path="figure-1-tmt-induced-freezing-cpa.html"><a href="figure-1-tmt-induced-freezing-cpa.html#conditioned-place-aversion-to-tmt"><i class="fa fa-check"></i>Conditioned Place Aversion to TMT</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="figure-2-basal-freezing-before-after-tmt.html"><a href="figure-2-basal-freezing-before-after-tmt.html"><i class="fa fa-check"></i>Figure 2: Basal Freezing Before &amp; After TMT</a>
<ul>
<li class="chapter" data-level="" data-path="figure-2-basal-freezing-before-after-tmt.html"><a href="figure-2-basal-freezing-before-after-tmt.html#time-spent-freezing-before-after-tmt"><i class="fa fa-check"></i>Time Spent Freezing Before / After TMT</a></li>
<li class="chapter" data-level="" data-path="figure-2-basal-freezing-before-after-tmt.html"><a href="figure-2-basal-freezing-before-after-tmt.html#freezing-frequency"><i class="fa fa-check"></i>Freezing Frequency</a></li>
<li class="chapter" data-level="" data-path="figure-2-basal-freezing-before-after-tmt.html"><a href="figure-2-basal-freezing-before-after-tmt.html#freezing-bout-length"><i class="fa fa-check"></i>Freezing Bout Length</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="figure-3-a-30-minute-tmt-exposure.html"><a href="figure-3-a-30-minute-tmt-exposure.html"><i class="fa fa-check"></i>Figure 3: A 30-Minute TMT Exposure</a>
<ul>
<li class="chapter" data-level="" data-path="figure-3-a-30-minute-tmt-exposure.html"><a href="figure-3-a-30-minute-tmt-exposure.html#time-spent-freezing-rearing-during-prolonged-tmt-exposure"><i class="fa fa-check"></i>Time Spent Freezing &amp; Rearing During Prolonged TMT Exposure</a></li>
<li class="chapter" data-level="" data-path="figure-3-a-30-minute-tmt-exposure.html"><a href="figure-3-a-30-minute-tmt-exposure.html#freezing-frequency-and-bout-duration"><i class="fa fa-check"></i>Freezing Frequency and Bout Duration</a></li>
<li class="chapter" data-level="" data-path="figure-3-a-30-minute-tmt-exposure.html"><a href="figure-3-a-30-minute-tmt-exposure.html#rearing-frequency-and-bout-duration"><i class="fa fa-check"></i>Rearing Frequency and Bout Duration</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="figure-4-a-second-tmt-exposure.html"><a href="figure-4-a-second-tmt-exposure.html"><i class="fa fa-check"></i>Figure 4: A Second TMT Exposure</a>
<ul>
<li class="chapter" data-level="" data-path="figure-4-a-second-tmt-exposure.html"><a href="figure-4-a-second-tmt-exposure.html#time-spent-rearing-and-freezing"><i class="fa fa-check"></i>Time Spent Rearing and Freezing</a></li>
<li class="chapter" data-level="" data-path="figure-4-a-second-tmt-exposure.html"><a href="figure-4-a-second-tmt-exposure.html#changes-in-freezing-across-the-session"><i class="fa fa-check"></i>Changes In Freezing Across the Session</a></li>
<li class="chapter" data-level="" data-path="figure-4-a-second-tmt-exposure.html"><a href="figure-4-a-second-tmt-exposure.html#freezing-frequency-1"><i class="fa fa-check"></i>Freezing Frequency</a></li>
<li class="chapter" data-level="" data-path="figure-4-a-second-tmt-exposure.html"><a href="figure-4-a-second-tmt-exposure.html#freezing-bout-duration"><i class="fa fa-check"></i>Freezing Bout Duration</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="figure-5-restraint-footshock-experiments.html"><a href="figure-5-restraint-footshock-experiments.html"><i class="fa fa-check"></i>Figure 5: Restraint / Footshock Experiments</a>
<ul>
<li class="chapter" data-level="" data-path="figure-5-restraint-footshock-experiments.html"><a href="figure-5-restraint-footshock-experiments.html#restraint-priming"><i class="fa fa-check"></i>Restraint Priming</a></li>
<li class="chapter" data-level="" data-path="figure-5-restraint-footshock-experiments.html"><a href="figure-5-restraint-footshock-experiments.html#footshock-priming"><i class="fa fa-check"></i>Footshock Priming</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="figure-1-tmt-induced-freezing-cpa" class="section level1 unnumbered hasAnchor">
<h1>Figure 1: TMT-Induced Freezing &amp; CPA<a href="figure-1-tmt-induced-freezing-cpa.html#figure-1-tmt-induced-freezing-cpa" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p><img src="Figs/1_TMT_Frz.png" width="1500" /></p>
<p><strong>Figure 1</strong>. (A) Mice are injected with saline or 50mg/kg metyrapone and exposed to 35μL of 10% TMT 30 min later. (B &amp; C) Raster plots showing individual episodes of freezing and rearing during TMT exposure. (D) Metyrapone administration prevents freezing behavior and increases rearing during TMT exposure. (E) Saline-treated mice exhibit increased freezing during the five-minute exposure to TMT, which is prevented by metyrapone administration. (F) Metyrapone reduces the number of freezing episodes and increases the number of rearing bouts during TMT exposure. (G) The average length of freezing episodes is reduced by metyrapone. (H) Saline-treated mice show longer bouts of freezing during the five minutes of TMT exposure, an effect prevented by metyrapone administration. (I) Schematic of the single-exposure conditioned place aversion paradigm. (J) During the pre-test, mice show strong preferences for one side of the conditioning apparatus. (K) The single pairing with TMT abolishes basal preferences. (L) Both saline- and metyrapone-treated mice exhibit a reduction in CPA score from pre-test to post-test, and there is no group difference in the magnitude of the change. Data presented as mean value <span class="math inline">\(\pm\)</span> SEM. * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001.</p>
<div id="behavioral-response-during-tmt-presentation" class="section level2 unnumbered hasAnchor">
<h2>Behavioral Response During TMT Presentation<a href="figure-1-tmt-induced-freezing-cpa.html#behavioral-response-during-tmt-presentation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="overall-time-spent-freezing-rearing" class="section level3 unnumbered hasAnchor">
<h3>Overall Time Spent Freezing / Rearing<a href="figure-1-tmt-induced-freezing-cpa.html#overall-time-spent-freezing-rearing" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To test whether CORT influenced behavioral responses to TMT, we pharmacologically inhibited its syntheses with metyrapone (Fig 1A).</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="figure-1-tmt-induced-freezing-cpa.html#cb1-1" tabindex="-1"></a>b <span class="ot">&lt;-</span> a <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="figure-1-tmt-induced-freezing-cpa.html#cb1-2" tabindex="-1"></a>  <span class="fu">group_by</span>(ID,Drug,Behavior) <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="figure-1-tmt-induced-freezing-cpa.html#cb1-3" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb1-4"><a href="figure-1-tmt-induced-freezing-cpa.html#cb1-4" tabindex="-1"></a>    <span class="at">sum=</span><span class="fu">sum</span>(Duration),</span>
<span id="cb1-5"><a href="figure-1-tmt-induced-freezing-cpa.html#cb1-5" tabindex="-1"></a>    <span class="at">Number=</span><span class="fu">n</span>(),</span>
<span id="cb1-6"><a href="figure-1-tmt-induced-freezing-cpa.html#cb1-6" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb1-7"><a href="figure-1-tmt-induced-freezing-cpa.html#cb1-7" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Perc =</span> (sum <span class="sc">/</span> <span class="dv">300</span>)<span class="sc">*</span><span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-8"><a href="figure-1-tmt-induced-freezing-cpa.html#cb1-8" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb1-9"><a href="figure-1-tmt-induced-freezing-cpa.html#cb1-9" tabindex="-1"></a></span>
<span id="cb1-10"><a href="figure-1-tmt-induced-freezing-cpa.html#cb1-10" tabindex="-1"></a><span class="fu">anova_test</span>(<span class="at">data =</span> b, <span class="at">dv =</span> Perc, <span class="at">within =</span> Behavior, <span class="at">wid =</span> ID, <span class="at">between =</span> Drug)</span></code></pre></div>
<pre><code>## ANOVA Table (type III tests)
## 
##          Effect DFn DFd      F            p p&lt;.05   ges
## 1          Drug   1  20 17.422 0.0004680000     * 0.257
## 2      Behavior   1  20  1.684 0.2090000000       0.048
## 3 Drug:Behavior   1  20 67.193 0.0000000799     * 0.670</code></pre>
<p>CORT-synthesis inhibition resulted in a change in the TMT-evoked behavioral profile (drug X behavior interaction: F<sub>1,20</sub> = 67.19, p &lt; 0.001). Compared to saline-injected controls, metyrapone-treated mice spent significantly less time freezing and more time rearing (Fig 1B,C,D).</p>
</div>
<div id="changes-in-freezing-across-the-5-minute-session" class="section level3 unnumbered hasAnchor">
<h3>Changes in Freezing Across the 5-minute Session<a href="figure-1-tmt-induced-freezing-cpa.html#changes-in-freezing-across-the-5-minute-session" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="figure-1-tmt-induced-freezing-cpa.html#cb3-1" tabindex="-1"></a>b <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="figure-1-tmt-induced-freezing-cpa.html#cb3-2" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="figure-1-tmt-induced-freezing-cpa.html#cb3-3" tabindex="-1"></a>  <span class="fu">filter</span>(Behavior <span class="sc">!=</span> <span class="st">&quot;groom&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="figure-1-tmt-induced-freezing-cpa.html#cb3-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Bins =</span> <span class="fu">cut</span>(</span>
<span id="cb3-5"><a href="figure-1-tmt-induced-freezing-cpa.html#cb3-5" tabindex="-1"></a>    Start_clean,</span>
<span id="cb3-6"><a href="figure-1-tmt-induced-freezing-cpa.html#cb3-6" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="cn">Inf</span>, <span class="dv">60</span>, <span class="dv">120</span>, <span class="dv">180</span>, <span class="dv">240</span>, <span class="sc">+</span><span class="cn">Inf</span>),</span>
<span id="cb3-7"><a href="figure-1-tmt-induced-freezing-cpa.html#cb3-7" tabindex="-1"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;1&quot;</span>, <span class="st">&quot;2&quot;</span>, <span class="st">&quot;3&quot;</span>, <span class="st">&quot;4&quot;</span>, <span class="st">&quot;5&quot;</span>)</span>
<span id="cb3-8"><a href="figure-1-tmt-induced-freezing-cpa.html#cb3-8" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb3-9"><a href="figure-1-tmt-induced-freezing-cpa.html#cb3-9" tabindex="-1"></a>  <span class="fu">group_by</span>(ID, Behavior, Drug, Bins) <span class="sc">%&gt;%</span></span>
<span id="cb3-10"><a href="figure-1-tmt-induced-freezing-cpa.html#cb3-10" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb3-11"><a href="figure-1-tmt-induced-freezing-cpa.html#cb3-11" tabindex="-1"></a>    <span class="at">sum=</span><span class="fu">sum</span>(Duration)</span>
<span id="cb3-12"><a href="figure-1-tmt-induced-freezing-cpa.html#cb3-12" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Perc =</span> (sum <span class="sc">/</span> <span class="dv">60</span>) <span class="sc">*</span> <span class="dv">100</span>)</span>
<span id="cb3-13"><a href="figure-1-tmt-induced-freezing-cpa.html#cb3-13" tabindex="-1"></a></span>
<span id="cb3-14"><a href="figure-1-tmt-induced-freezing-cpa.html#cb3-14" tabindex="-1"></a>c <span class="ot">&lt;-</span> b <span class="sc">%&gt;%</span></span>
<span id="cb3-15"><a href="figure-1-tmt-induced-freezing-cpa.html#cb3-15" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb3-16"><a href="figure-1-tmt-induced-freezing-cpa.html#cb3-16" tabindex="-1"></a>  <span class="fu">filter</span>(Behavior <span class="sc">==</span> <span class="st">&quot;freeze&quot;</span>)</span>
<span id="cb3-17"><a href="figure-1-tmt-induced-freezing-cpa.html#cb3-17" tabindex="-1"></a></span>
<span id="cb3-18"><a href="figure-1-tmt-induced-freezing-cpa.html#cb3-18" tabindex="-1"></a><span class="fu">anova_test</span>(<span class="at">data =</span> c, <span class="at">dv =</span> Perc, <span class="at">within =</span> Bins, <span class="at">wid =</span> ID, <span class="at">between =</span> Drug)</span></code></pre></div>
<pre><code>## ANOVA Table (type III tests)
## 
## $ANOVA
##      Effect DFn DFd      F        p p&lt;.05   ges
## 1      Drug   1   8 35.432 0.000341     * 0.417
## 2      Bins   4  32  6.006 0.001000     * 0.386
## 3 Drug:Bins   4  32  4.800 0.004000     * 0.335
## 
## $`Mauchly&#39;s Test for Sphericity`
##      Effect     W     p p&lt;.05
## 1      Bins 0.085 0.079      
## 2 Drug:Bins 0.085 0.079      
## 
## $`Sphericity Corrections`
##      Effect   GGe      DF[GG] p[GG] p[GG]&lt;.05   HFe      DF[HF] p[HF] p[HF]&lt;.05
## 1      Bins 0.519 2.08, 16.62 0.010         * 0.705 2.82, 22.56 0.004         *
## 2 Drug:Bins 0.519 2.08, 16.62 0.022         * 0.705 2.82, 22.56 0.011         *</code></pre>
<p>Freezing increased over the five minute TMT exposure in saline-injected mice, whereas metyrapone-treated mice did not show this time-dependent increase (drug X time interaction: F<sub>4,32</sub> = 4.80, p = 0.004; Fig 1E).</p>
</div>
<div id="number-of-freezing-rearing-episodes" class="section level3 unnumbered hasAnchor">
<h3>Number of Freezing / Rearing Episodes<a href="figure-1-tmt-induced-freezing-cpa.html#number-of-freezing-rearing-episodes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="figure-1-tmt-induced-freezing-cpa.html#cb5-1" tabindex="-1"></a>b <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="figure-1-tmt-induced-freezing-cpa.html#cb5-2" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="figure-1-tmt-induced-freezing-cpa.html#cb5-3" tabindex="-1"></a>  <span class="fu">filter</span>(Behavior <span class="sc">!=</span> <span class="st">&quot;groom&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb5-4"><a href="figure-1-tmt-induced-freezing-cpa.html#cb5-4" tabindex="-1"></a>  <span class="fu">group_by</span>(ID,Drug,Behavior) <span class="sc">%&gt;%</span></span>
<span id="cb5-5"><a href="figure-1-tmt-induced-freezing-cpa.html#cb5-5" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb5-6"><a href="figure-1-tmt-induced-freezing-cpa.html#cb5-6" tabindex="-1"></a>    <span class="at">n=</span><span class="fu">n</span>()</span>
<span id="cb5-7"><a href="figure-1-tmt-induced-freezing-cpa.html#cb5-7" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb5-8"><a href="figure-1-tmt-induced-freezing-cpa.html#cb5-8" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb5-9"><a href="figure-1-tmt-induced-freezing-cpa.html#cb5-9" tabindex="-1"></a></span>
<span id="cb5-10"><a href="figure-1-tmt-induced-freezing-cpa.html#cb5-10" tabindex="-1"></a><span class="fu">anova_test</span>(<span class="at">data =</span> b, <span class="at">dv =</span> n, <span class="at">within =</span> Behavior, <span class="at">wid =</span> ID, <span class="at">between =</span> Drug)</span></code></pre></div>
<pre><code>## ANOVA Table (type III tests)
## 
##          Effect DFn DFd      F             p p&lt;.05   ges
## 1          Drug   1  20  1.071 0.31300000000       0.020
## 2      Behavior   1  20  1.618 0.21800000000       0.048
## 3 Drug:Behavior   1  20 97.941 0.00000000377     * 0.753</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="figure-1-tmt-induced-freezing-cpa.html#cb7-1" tabindex="-1"></a>b <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="figure-1-tmt-induced-freezing-cpa.html#cb7-2" tabindex="-1"></a>  <span class="fu">group_by</span>(Drug) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="figure-1-tmt-induced-freezing-cpa.html#cb7-3" tabindex="-1"></a>  <span class="fu">pairwise_t_test</span>(n <span class="sc">~</span> Behavior, <span class="at">paired =</span> T)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 11
##   Drug       .y.   group1 group2    n1    n2 statistic    df          p    p.adj
## * &lt;fct&gt;      &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;
## 1 Saline     n     freeze rear      10    10      6.26     9 0.000147    1.47e-4
## 2 Metyrapone n     freeze rear      12    12     -7.87    11 0.00000762  7.62e-6
## # ℹ 1 more variable: p.adj.signif &lt;chr&gt;</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="figure-1-tmt-induced-freezing-cpa.html#cb9-1" tabindex="-1"></a>b <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="figure-1-tmt-induced-freezing-cpa.html#cb9-2" tabindex="-1"></a>  <span class="fu">group_by</span>(Behavior) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="figure-1-tmt-induced-freezing-cpa.html#cb9-3" tabindex="-1"></a>  <span class="fu">pairwise_t_test</span>(n <span class="sc">~</span> Drug)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 10
##   Behavior .y.   group1 group2    n1    n2       p p.signif   p.adj p.adj.signif
## * &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;       
## 1 freeze   n     Saline Metyr…    10    12 6.29e-8 ****     6.29e-8 ****        
## 2 rear     n     Saline Metyr…    10    12 4.9 e-7 ****     4.9 e-7 ****</code></pre>
<p>In addition, metyrapone reduced freezing frequency and increased rearing frequency during TMT (drug X behavior interaction: F<sub>1,20</sub> = 97.94, p &lt; 0.001; Fig 1F).</p>
</div>
<div id="bout-duration-for-freezing-and-rearing" class="section level3 unnumbered hasAnchor">
<h3>Bout Duration for Freezing and Rearing<a href="figure-1-tmt-induced-freezing-cpa.html#bout-duration-for-freezing-and-rearing" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="figure-1-tmt-induced-freezing-cpa.html#cb11-1" tabindex="-1"></a>anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(Duration <span class="sc">~</span> Behavior <span class="sc">*</span> Drug, <span class="at">data =</span> a)</span>
<span id="cb11-2"><a href="figure-1-tmt-induced-freezing-cpa.html#cb11-2" tabindex="-1"></a><span class="fu">summary</span>(anova)</span></code></pre></div>
<pre><code>##                 Df Sum Sq Mean Sq F value       Pr(&gt;F)    
## Behavior         1     58   57.66   15.71 0.0000792220 ***
## Drug             1     82   81.82   22.29 0.0000026787 ***
## Behavior:Drug    1    114  113.94   31.04 0.0000000324 ***
## Residuals     1015   3726    3.67                         
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="figure-1-tmt-induced-freezing-cpa.html#cb13-1" tabindex="-1"></a>a <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="figure-1-tmt-induced-freezing-cpa.html#cb13-2" tabindex="-1"></a>  <span class="fu">group_by</span>(Behavior) <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="figure-1-tmt-induced-freezing-cpa.html#cb13-3" tabindex="-1"></a>  <span class="fu">pairwise_t_test</span>(Duration <span class="sc">~</span> Drug)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 10
##   Behavior .y.   group1 group2    n1    n2       p p.signif   p.adj p.adj.signif
## * &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt;       
## 1 freeze   Dura… Saline Metyr…   344   109 4.13e-7 ****     4.13e-7 ****        
## 2 rear     Dura… Saline Metyr…   140   426 7.07e-1 ns       7.07e-1 ns</code></pre>
<p>The average length of freezing epochs was longer for saline- compared to metyrapone-treated mice (p &lt; 0.001; Fig 1G), but there was no difference in the average length of rearing episodes (p = 0.71; Fig 1G).</p>
</div>
<div id="changes-in-bout-length-of-freezing-across-the-5-minute-session" class="section level3 unnumbered hasAnchor">
<h3>Changes in Bout Length of Freezing Across the 5-minute Session<a href="figure-1-tmt-induced-freezing-cpa.html#changes-in-bout-length-of-freezing-across-the-5-minute-session" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="figure-1-tmt-induced-freezing-cpa.html#cb15-1" tabindex="-1"></a>b <span class="ot">&lt;-</span> a <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="figure-1-tmt-induced-freezing-cpa.html#cb15-2" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="figure-1-tmt-induced-freezing-cpa.html#cb15-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Bins =</span> <span class="fu">cut</span>(</span>
<span id="cb15-4"><a href="figure-1-tmt-induced-freezing-cpa.html#cb15-4" tabindex="-1"></a>    Start_clean,</span>
<span id="cb15-5"><a href="figure-1-tmt-induced-freezing-cpa.html#cb15-5" tabindex="-1"></a>    <span class="at">breaks =</span> <span class="dv">5</span>,</span>
<span id="cb15-6"><a href="figure-1-tmt-induced-freezing-cpa.html#cb15-6" tabindex="-1"></a>    <span class="at">labels=</span><span class="fu">c</span>(<span class="st">&quot;1&quot;</span>,<span class="st">&quot;2&quot;</span>,<span class="st">&quot;3&quot;</span>,<span class="st">&quot;4&quot;</span>,<span class="st">&quot;5&quot;</span>)</span>
<span id="cb15-7"><a href="figure-1-tmt-induced-freezing-cpa.html#cb15-7" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb15-8"><a href="figure-1-tmt-induced-freezing-cpa.html#cb15-8" tabindex="-1"></a>  <span class="fu">group_by</span>(ID, Behavior, Drug, Bins) <span class="sc">%&gt;%</span></span>
<span id="cb15-9"><a href="figure-1-tmt-induced-freezing-cpa.html#cb15-9" tabindex="-1"></a>  <span class="fu">filter</span>(Behavior <span class="sc">==</span> <span class="st">&quot;freeze&quot;</span>)</span>
<span id="cb15-10"><a href="figure-1-tmt-induced-freezing-cpa.html#cb15-10" tabindex="-1"></a></span>
<span id="cb15-11"><a href="figure-1-tmt-induced-freezing-cpa.html#cb15-11" tabindex="-1"></a>anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(Duration<span class="sc">~</span>Bins<span class="sc">*</span>Drug,<span class="at">data=</span>b)</span>
<span id="cb15-12"><a href="figure-1-tmt-induced-freezing-cpa.html#cb15-12" tabindex="-1"></a><span class="fu">summary</span>(anova)</span></code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value             Pr(&gt;F)    
## Bins          4  451.9  112.97  18.071 0.0000000000000925 ***
## Drug          1  203.2  203.17  32.499 0.0000000218006710 ***
## Bins:Drug     4  113.2   28.30   4.527            0.00136 ** 
## Residuals   443 2769.5    6.25                               
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The length of freezing episodes increased across the five minute TMT exposure for saline-injected mice, but not for metyrapone-treated mice (drug X time interaction: F<sub>4,443</sub> = 4.53, p = 0.001; Fig 1H). These results indicate that blocking CORT synthesis during TMT exposure shifts the defensive response from predominantly freezing to primarily rearing.</p>
</div>
</div>
<div id="conditioned-place-aversion-to-tmt" class="section level2 unnumbered hasAnchor">
<h2>Conditioned Place Aversion to TMT<a href="figure-1-tmt-induced-freezing-cpa.html#conditioned-place-aversion-to-tmt" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Next, to understand whether mice developed an aversion to the context where they previously encountered TMT, we conducted a conditioned place aversion test (Fig 1I).</p>
<div id="baseline-preferences" class="section level3 unnumbered hasAnchor">
<h3>Baseline Preferences<a href="figure-1-tmt-induced-freezing-cpa.html#baseline-preferences" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="figure-1-tmt-induced-freezing-cpa.html#cb17-1" tabindex="-1"></a><span class="fu">t.test</span>(BL_pref_data<span class="sc">$</span>Tm_White, BL_pref_data<span class="sc">$</span>Tm_Black, <span class="at">paired =</span> T)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  BL_pref_data$Tm_White and BL_pref_data$Tm_Black
## t = -5.049, df = 23, p-value = 0.00004131
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  -46.77726 -19.58690
## sample estimates:
## mean difference 
##       -33.18208</code></pre>
<p>Mice exhibited robust side preferences at baseline (t<sub>23</sub> = 5.05, p &lt; 0.001), and TMT was paired with the side of the apparatus that each mouse exhibited a baseline preference for (Fig 1J).</p>
</div>
<div id="test-session" class="section level3 unnumbered hasAnchor">
<h3>Test Session<a href="figure-1-tmt-induced-freezing-cpa.html#test-session" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="cpa-for-each-drug-group" class="section level4 unnumbered hasAnchor">
<h4>CPA for Each Drug Group<a href="figure-1-tmt-induced-freezing-cpa.html#cpa-for-each-drug-group" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="figure-1-tmt-induced-freezing-cpa.html#cb19-1" tabindex="-1"></a>s <span class="ot">&lt;-</span> Test_data[Test_data<span class="sc">$</span>Drug <span class="sc">==</span> <span class="st">&quot;Saline&quot;</span>, ]</span>
<span id="cb19-2"><a href="figure-1-tmt-induced-freezing-cpa.html#cb19-2" tabindex="-1"></a>m <span class="ot">&lt;-</span> Test_data[Test_data<span class="sc">$</span>Drug <span class="sc">==</span> <span class="st">&quot;Metyrapone&quot;</span>, ]</span>
<span id="cb19-3"><a href="figure-1-tmt-induced-freezing-cpa.html#cb19-3" tabindex="-1"></a></span>
<span id="cb19-4"><a href="figure-1-tmt-induced-freezing-cpa.html#cb19-4" tabindex="-1"></a><span class="fu">t.test</span>(s<span class="sc">$</span>Pref_tm, s<span class="sc">$</span>Non_Pref_tm, <span class="at">paired =</span> T)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  s$Pref_tm and s$Non_Pref_tm
## t = -1.2068, df = 11, p-value = 0.2528
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  -60.60959  17.68126
## sample estimates:
## mean difference 
##       -21.46417</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="figure-1-tmt-induced-freezing-cpa.html#cb21-1" tabindex="-1"></a><span class="fu">t.test</span>(m<span class="sc">$</span>Pref_tm, m<span class="sc">$</span>Non_Pref_tm, <span class="at">paired =</span> T)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  m$Pref_tm and m$Non_Pref_tm
## t = -1.3417, df = 11, p-value = 0.2067
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  -53.31831  12.93164
## sample estimates:
## mean difference 
##       -20.19333</code></pre>
<p>Preferences for the initially preferred side of the apparatus were abolished by the single pairing with TMT for both saline- and metyrapone-treated mice (both p values &gt; 0.2 during the post-test; Fig 1K).</p>
</div>
<div id="change-in-preference-between-the-baseline-and-test-sessions" class="section level4 unnumbered hasAnchor">
<h4>Change in Preference Between the Baseline and Test Sessions<a href="figure-1-tmt-induced-freezing-cpa.html#change-in-preference-between-the-baseline-and-test-sessions" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="figure-1-tmt-induced-freezing-cpa.html#cb23-1" tabindex="-1"></a><span class="fu">t.test</span>(a<span class="sc">$</span>BL_CPA_score, a<span class="sc">$</span>Post_CPA_score, <span class="at">paired =</span> T)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  a$BL_CPA_score and a$Post_CPA_score
## t = 2.6027, df = 10, p-value = 0.02637
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  0.09237031 1.19126470
## sample estimates:
## mean difference 
##       0.6418175</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="figure-1-tmt-induced-freezing-cpa.html#cb25-1" tabindex="-1"></a><span class="fu">t.test</span>(b<span class="sc">$</span>BL_CPA_score, b<span class="sc">$</span>Post_CPA_score, <span class="at">paired =</span> T)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  b$BL_CPA_score and b$Post_CPA_score
## t = 4.0866, df = 11, p-value = 0.0018
## alternative hypothesis: true mean difference is not equal to 0
## 95 percent confidence interval:
##  0.2529397 0.8434275
## sample estimates:
## mean difference 
##       0.5481836</code></pre>
<p>Both groups exhibited a reduction in CPA score after the single TMT exposure, indicating conditioned place aversion (saline t<sub>10</sub> = 2.60, p = 0.026; metyrapone t<sub>11</sub> = 4.09, p = 0.002; Fig 1L).</p>
</div>
<div id="compare-cpa-scores-for-saline-and-metyrapone-mice" class="section level4 unnumbered hasAnchor">
<h4>Compare CPA Scores for Saline and Metyrapone Mice<a href="figure-1-tmt-induced-freezing-cpa.html#compare-cpa-scores-for-saline-and-metyrapone-mice" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="figure-1-tmt-induced-freezing-cpa.html#cb27-1" tabindex="-1"></a><span class="fu">t.test</span>(delta_CPA_score <span class="sc">~</span> Drug, <span class="at">data =</span> A_A)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  delta_CPA_score by Drug
## t = -0.33355, df = 15.556, p-value = 0.7432
## alternative hypothesis: true difference in means between group Saline and group Metyrapone is not equal to 0
## 95 percent confidence interval:
##  -0.6901155  0.5028477
## sample estimates:
##     mean in group Saline mean in group Metyrapone 
##               -0.6418175               -0.5481836</code></pre>
<p>Metyrapone treatment during TMT did not alter the magnitude of the change in CPA score between sessions (p = 0.74; Fig 1L).</p>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="figure-2-basal-freezing-before-after-tmt.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["_main.pdf", "_main.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "edit": "https://github.com/USERNAME/REPO/edit/BRANCH/%s",
    "download": ["pdf", "epub"]
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
